# Russian translation for furiusisomount
# Copyright (c) 2010 Rosetta Contributors and Canonical Ltd 2010
# This file is distributed under the same license as the furiusisomount package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: furiusisomount\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2010-08-25 11:45+0100\n"
"PO-Revision-Date: 2011-08-01 08:33+0000\n"
"Last-Translator: Лев Логинов <Unknown>\n"
"Language-Team: Russian <ru@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-03-21 04:48+0000\n"
"X-Generator: Launchpad (build 16532)\n"

#: aboutbox.py:35
msgid "translator-credits"
msgstr ""
"Launchpad Contributions:\n"
"  Alexander 'FONTER' Zinin https://launchpad.net/~spore-09\n"
"  Alexey Ivanov https://launchpad.net/~alexey-ivanov\n"
"  Лев Логинов https://launchpad.net/~ghost1513-ghostware"

#: aboutbox.py:40
msgid "Developer:"
msgstr "Разработчик:"

#: filehash.py:25 filehash.py:36 main.py:246
msgid "Calculating, please wait..."
msgstr "Расчет, подождите пожалуйста ..."

#: globals.py:22
msgid "Furius ISO Mount Tool"
msgstr "Furius ISO Mount Tool"

#: globals.py:23
msgid ""
"Simple Gtk+ Interface to Mount ISO, IMG, BIN, MDF and NRG Image files "
"without burning to disk."
msgstr ""
"Простой интерфейс GTK+ для монтирования ISO, IMG, BIN и NRG файлов образов "
"без необходимости записывать на диск."

#: imageaction.py:35 imageaction.py:58 imageaction.py:69 imageaction.py:79
#: main.py:83 main.py:340 main.py:386
#, python-format
msgid ""
"Error mounting image.\n"
"Unexpected error: %s"
msgstr ""
"Ошибка при монтировании образа.\n"
"Непредвиденная ошибка: %s"

#: imageaction.py:36
msgid "Defaulting to home directory for mounting."
msgstr "По умолчанию используется домашний каталог для монтирования."

#: imageaction.py:55
#, python-format
msgid ""
"%s successfully mounted @ %s. If required, run the following commands to "
"remove:\n"
"  :fusermount -u %s\n"
"  :rmdir %s"
msgstr ""
"%s успешно смонтирован @ %s. При необходимости, выполните следующие команды "
"для удаления.\n"
"  :fusermount -u %s\n"
"  :rmdir %s"

#: imageaction.py:66
#, python-format
msgid ""
"%s successfully mounted @ %s. If required, run the following commands to "
"remove:\n"
"  :gksu -u root umount %s\n"
"  :rmdir %s"
msgstr ""
"%s успешно смонтирован @ %s. При необходимости, выполните следующие команды "
"для удаления.\n"
"  :gksu -u root umount %s\n"
"  :rmdir %s"

#: imageaction.py:76 main.py:79 main.py:336 main.py:382
#, python-format
msgid ""
"Error mounting image.\n"
"OS error(%s): %s"
msgstr ""
"Ошибка при монтировании образа.\n"
"OS error(%s): %s"

#: imageaction.py:103
#, python-format
msgid ""
"Error saving history to file.\n"
"OS error(%s): %s"
msgstr ""
"Ошибка сохранения истории в файл.\n"
"OS error(%s): %s"

#: imageaction.py:106
#, python-format
msgid ""
"Error saving history to file\n"
"Unexpected error: %s"
msgstr ""
"Ошибка сохранения истории в файл.\n"
"Непредвиденная ошибка: %s"

#: imageaction.py:128
#, python-format
msgid "%s successfully unmounted."
msgstr "%s успешно размонтирован."

#: imageaction.py:130 main.py:358 main.py:401
#, python-format
msgid ""
"Error unmounting image.\n"
"Unexpected error: %s"
msgstr ""
"Ошибка при размонтировании образа.\n"
"Непредвиденная ошибка: %s"

#: imageaction.py:142 main.py:364
#, python-format
msgid ""
"Error burning image.\n"
"Unexpected error: %s"
msgstr ""
"Ошибка при записи образа.\n"
"Непредвиденная ошибка: %s"

#: imageaction.py:152
#, python-format
msgid ""
"Error launching nautilus.\n"
"Unexpected error: %s"
msgstr ""
"Ошибка запуска nautilus.\n"
"Непредвиденная ошибка: %s"

#: main.py:51
msgid "Application started..."
msgstr "Программа запущена..."

#: main.py:81 main.py:338 main.py:384
#, python-format
msgid ""
"Error mounting image.\n"
"IO error(%s): %s"
msgstr ""
"Ошибка при монтировании образа.\n"
"IO error(%s): %s"

#: main.py:95 main.py:112
#, python-format
msgid ""
"Error loading history.\n"
"OS error(%s): %s"
msgstr ""
"Ошибка при загрузке истории.\n"
"OS error(%s): %s"

#: main.py:97 main.py:114
#, python-format
msgid ""
"Error loading history.\n"
"Unexpected error: %s"
msgstr ""
"Ошибка при загрузке истории.\n"
"Непредвиденная ошибка: %s"

#: main.py:125
#, python-format
msgid ""
"Error creating settings directory.\n"
"OS error(%s): %s"
msgstr ""
"Ошибка при создании каталога настроек.\n"
"OS error(%s): %s"

#: main.py:127
#, python-format
msgid ""
"Error creating settings directory.\n"
"IO error(%s): %s"
msgstr ""
"Ошибка при создании каталога настроек.\n"
"IO error(%s): %s"

#: main.py:129
#, python-format
msgid ""
"Error creating settings directory.\n"
"Unexpected error: %s"
msgstr ""
"Ошибка при создании каталога настроек.\n"
"Непредвиденная ошибка: %s"

#: main.py:139
#, python-format
msgid "New settings file created at %s"
msgstr "Новый файл настроек создан в %s"

#: main.py:141
#, python-format
msgid ""
"Error creating settings file.\n"
"OS error(%s): %s"
msgstr ""
"Ошибка при создании файла настроек.\n"
"OS error(%s): %s"

#: main.py:143
#, python-format
msgid ""
"Error creating settings file.\n"
"IO error(%s): %s"
msgstr ""
"Ошибка при создании файла настроек.\n"
"IO error(%s): %s"

#: main.py:145
#, python-format
msgid ""
"Error creating settings file.\n"
"Unexpected error: %s"
msgstr ""
"Ошибка при создании файла настроек.\n"
"Непредвиденная ошибка: %s"

#: main.py:159
msgid "_Browse..."
msgstr "_Обзор..."

#: main.py:163
msgid "_Mount"
msgstr "_Подключить"

#: main.py:167 main.py:234 main.py:260
msgid "_Checksum"
msgstr "_Конт. сумма"

#: main.py:171
msgid "Bur_n"
msgstr "Записать"

#: main.py:175
msgid "_Unmount"
msgstr "_Отключить"

#: main.py:176
msgid "View Log"
msgstr "Просмотреть журнал"

#: main.py:177
msgid "Delete Log"
msgstr "Удалить журнал"

#: main.py:178
msgid "Select Image"
msgstr "Выбрать образ"

#: main.py:179 main.py:289 main.py:308
msgid "No Image Selected"
msgstr "Не выбран образ"

#: main.py:181 main.py:248
msgid "No Checksum Generated"
msgstr "Контрольная сумма не сгененрирована"

#: main.py:183 main.py:355
msgid "No Mount Point Selected"
msgstr "Не выбрана точка монтирования"

#: main.py:185
msgid "Mounted Images:"
msgstr "Подключеные образы:"

#: main.py:186
msgid "Drag image files into above window to quickly mount"
msgstr "Перетащите файлы образов в окно выше, чтобы быстро их подключить"

#: main.py:196
msgid "Mount Point"
msgstr "Точка подключения"

#: main.py:197
msgid "Image File"
msgstr "Файл образа"

#: main.py:236
msgid "_Cancel"
msgstr "_Отмена"

#: main.py:240
msgid "Checksum generation started..."
msgstr "Вычисление контрольной суммы..."

#: main.py:256
#, python-format
msgid "%s:%s"
msgstr "%s:%s"

#: main.py:259
msgid "Checksum generation aborted!"
msgstr "Вычисление контрольной суммы прервано!"

#: main.py:268
msgid "Open Image.."
msgstr "Открыть образ..."

#: main.py:288
msgid ""
"File not found. \n"
"Please check source exists."
msgstr ""
"Файл не найден. \n"
"Пожалуйста, проверьте источник."

#: main.py:307
msgid ""
"File does not appear to be a compatible Image. \n"
"Please check source."
msgstr ""
"Файл образа не поддерживается. \n"
"Пожалуйста, проверьте источник."

#: main.py:318
#, python-format
msgid "%s not found."
msgstr "%s не найден."

#: main.py:322
msgid "Are you sure you wish to delete the log?"
msgstr "Вы уверены, что хотите удалить журнал?"

#: main.py:326 main.py:328
#, python-format
msgid ""
"Error deleting log.\n"
"OS error(%s): %s"
msgstr ""
"Ошибка при удалении журнала.\n"
"OS error(%s): %s"

#: main.py:330
#, python-format
msgid ""
"Error deleting log.\n"
"Unexpected error: %s"
msgstr ""
"Ошибка при удалении журнала.\n"
"Непредвиденная ошибка: %s"

#: main.py:393
msgid "Application closed!"
msgstr "Программа закрыта!"

#: main.py:397
#, python-format
msgid ""
"%s is still mounted.\n"
"Do you wish to unmount it before exiting?"
msgstr ""
"%s всё ещё подключен.\n"
"Вы хотите, чтобы отключить его перед выходом?"

#: main.py:408
#, python-format
msgid ""
"Error saving unmounted images to file.\n"
"OS error(%s): %s"
msgstr ""
"Ошибка при сохранении размонтированных образов в файл.\n"
"OS error(%s): %s"

#: main.py:410
#, python-format
msgid ""
"Error saving unmounted images to file\n"
"Unexpected error: %s"
msgstr ""
"Ошибка при сохранении размонтированных образов в файл.\n"
"Непредвиденная ошибка: %s"
