# Brazilian Portuguese translation for furiusisomount
# Copyright (c) 2010 Rosetta Contributors and Canonical Ltd 2010
# This file is distributed under the same license as the furiusisomount package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: furiusisomount\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2010-08-25 11:45+0100\n"
"PO-Revision-Date: 2011-03-07 04:14+0000\n"
"Last-Translator: Adriano Steffler <Unknown>\n"
"Language-Team: Brazilian Portuguese <pt_BR@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-03-21 04:48+0000\n"
"X-Generator: Launchpad (build 16532)\n"

#: aboutbox.py:35
msgid "translator-credits"
msgstr ""
"Launchpad Contributions:\n"
"  Adriano Steffler https://launchpad.net/~adrianosteffler"

#: aboutbox.py:40
msgid "Developer:"
msgstr "Desenvolvedor:"

#: filehash.py:25 filehash.py:36 main.py:246
msgid "Calculating, please wait..."
msgstr "Calculando, por favor aguarde..."

#: globals.py:22
msgid "Furius ISO Mount Tool"
msgstr "Ferramenta do Furius ISO Mount"

#: globals.py:23
msgid ""
"Simple Gtk+ Interface to Mount ISO, IMG, BIN, MDF and NRG Image files "
"without burning to disk."
msgstr ""
"Uma interface Gtk+ simples para montar arquivos de imagem ISO, IMG, BIN, MDF "
"e NRG sem gravá-los em um disco."

#: imageaction.py:35 imageaction.py:58 imageaction.py:69 imageaction.py:79
#: main.py:83 main.py:340 main.py:386
#, python-format
msgid ""
"Error mounting image.\n"
"Unexpected error: %s"
msgstr ""
"Erro ao montar a imagem.\n"
"Erro inesperado: %s"

#: imageaction.py:36
msgid "Defaulting to home directory for mounting."
msgstr "Usando o diretório home como o padrão no processo de montagem"

#: imageaction.py:55
#, python-format
msgid ""
"%s successfully mounted @ %s. If required, run the following commands to "
"remove:\n"
"  :fusermount -u %s\n"
"  :rmdir %s"
msgstr ""
"%s foi montado com sucesso @ %s. Caso seja requerido, execute os seguintes "
"comandos para remover:\n"
"  :fusermount -u %s\n"
"  :rmdir %s"

#: imageaction.py:66
#, python-format
msgid ""
"%s successfully mounted @ %s. If required, run the following commands to "
"remove:\n"
"  :gksu -u root umount %s\n"
"  :rmdir %s"
msgstr ""
"%s foi montado com sucesso @ %s. Caso seja requerido, execute os seguintes "
"comandos para remover:\n"
"  :gksu -u root umount %s\n"
"  :rmdir %s"

#: imageaction.py:76 main.py:79 main.py:336 main.py:382
#, python-format
msgid ""
"Error mounting image.\n"
"OS error(%s): %s"
msgstr ""
"Erro ao montar a imagem.\n"
"Erro de SO(%s): %s"

#: imageaction.py:103
#, python-format
msgid ""
"Error saving history to file.\n"
"OS error(%s): %s"
msgstr ""
"Erro ao salvar o histórico em um arquivo.\n"
"Erro de SO(%s): %s"

#: imageaction.py:106
#, python-format
msgid ""
"Error saving history to file\n"
"Unexpected error: %s"
msgstr ""
"Erro ao salvar o histórico em um arquivo.\n"
"Erro inesperado: %s"

#: imageaction.py:128
#, python-format
msgid "%s successfully unmounted."
msgstr "%s foi desmontado com sucesso."

#: imageaction.py:130 main.py:358 main.py:401
#, python-format
msgid ""
"Error unmounting image.\n"
"Unexpected error: %s"
msgstr ""
"Erro ao desmontar a imagem.\n"
"Erro inesperado: %s"

#: imageaction.py:142 main.py:364
#, python-format
msgid ""
"Error burning image.\n"
"Unexpected error: %s"
msgstr ""
"Erro ao gravar a imagem.\n"
"Erro inesperado: %s"

#: imageaction.py:152
#, python-format
msgid ""
"Error launching nautilus.\n"
"Unexpected error: %s"
msgstr ""
"Erro ao iniciar o Nautilus.\n"
"Erro inesperado: %s"

#: main.py:51
msgid "Application started..."
msgstr "O aplicativo foi iniciado..."

#: main.py:81 main.py:338 main.py:384
#, python-format
msgid ""
"Error mounting image.\n"
"IO error(%s): %s"
msgstr ""
"Erro ao montar a imagem.\n"
"Erro de E/S(%s): %s"

#: main.py:95 main.py:112
#, python-format
msgid ""
"Error loading history.\n"
"OS error(%s): %s"
msgstr ""
"Erro ao carregar o histórico.\n"
"Erro de SO(%s): %s"

#: main.py:97 main.py:114
#, python-format
msgid ""
"Error loading history.\n"
"Unexpected error: %s"
msgstr ""
"Erro ao carregar o histórico.\n"
"Erro inesperado: %s"

#: main.py:125
#, python-format
msgid ""
"Error creating settings directory.\n"
"OS error(%s): %s"
msgstr ""
"Erro ao criar o diretório de configurações.\n"
"Erro de SO(%s): %s"

#: main.py:127
#, python-format
msgid ""
"Error creating settings directory.\n"
"IO error(%s): %s"
msgstr ""
"Erro ao criar o diretório de configurações.\n"
"Erro de E/S(%s): %s"

#: main.py:129
#, python-format
msgid ""
"Error creating settings directory.\n"
"Unexpected error: %s"
msgstr ""
"Erro ao criar o diretório de configurações.\n"
"Erro inesperado: %s"

#: main.py:139
#, python-format
msgid "New settings file created at %s"
msgstr "Um novo arquivo de configurações foi criado em %s"

#: main.py:141
#, python-format
msgid ""
"Error creating settings file.\n"
"OS error(%s): %s"
msgstr ""
"Erro ao criar o arquivo de configurações.\n"
"Erro de SO(%s): %s"

#: main.py:143
#, python-format
msgid ""
"Error creating settings file.\n"
"IO error(%s): %s"
msgstr ""
"Erro ao criar o arquivo de configurações.\n"
"Erro de E/S(%s): %s"

#: main.py:145
#, python-format
msgid ""
"Error creating settings file.\n"
"Unexpected error: %s"
msgstr ""
"Erro ao criar o arquivo de configurações.\n"
"Erro inesperado: %s"

#: main.py:159
msgid "_Browse..."
msgstr "_Navegar..."

#: main.py:163
msgid "_Mount"
msgstr "_Montar"

#: main.py:167 main.py:234 main.py:260
msgid "_Checksum"
msgstr "_Soma de verificação"

#: main.py:171
msgid "Bur_n"
msgstr "_Gravar"

#: main.py:175
msgid "_Unmount"
msgstr "_Desmontar"

#: main.py:176
msgid "View Log"
msgstr "Visualizar registro do histórico"

#: main.py:177
msgid "Delete Log"
msgstr "Excluir registro do histórico"

#: main.py:178
msgid "Select Image"
msgstr "Selecione uma imagem"

#: main.py:179 main.py:289 main.py:308
msgid "No Image Selected"
msgstr "Nenhuma imagem selecionada"

#: main.py:181 main.py:248
msgid "No Checksum Generated"
msgstr "Nenhuma soma de verificação foi gerada"

#: main.py:183 main.py:355
msgid "No Mount Point Selected"
msgstr "Nenhum ponto de montagem selecionado"

#: main.py:185
msgid "Mounted Images:"
msgstr "Imagens montadas:"

#: main.py:186
msgid "Drag image files into above window to quickly mount"
msgstr ""
"Arraste arquivos de imagem para dentro da janela acima, a fim de montá-los "
"rapidamente"

#: main.py:196
msgid "Mount Point"
msgstr "Ponto de montagem"

#: main.py:197
msgid "Image File"
msgstr "Arquivo de imagem"

#: main.py:236
msgid "_Cancel"
msgstr "_Cancelar"

#: main.py:240
msgid "Checksum generation started..."
msgstr "Geração de soma de verificação iniciada..."

#: main.py:256
#, python-format
msgid "%s:%s"
msgstr "%s:%s"

#: main.py:259
msgid "Checksum generation aborted!"
msgstr "Geração de soma de verificação cancelada!"

#: main.py:268
msgid "Open Image.."
msgstr "Abrir imagem..."

#: main.py:288
msgid ""
"File not found. \n"
"Please check source exists."
msgstr ""
"O arquivo não foi encontrado. \n"
"Por favor, verifique se o arquivo existe."

#: main.py:307
msgid ""
"File does not appear to be a compatible Image. \n"
"Please check source."
msgstr ""
"O arquivo parece não ser uma imagem compatível. \n"
"Por favor, verifique a sua origem."

#: main.py:318
#, python-format
msgid "%s not found."
msgstr "%s não foi encontrado."

#: main.py:322
msgid "Are you sure you wish to delete the log?"
msgstr "Você tem certeza que quer excluir o registro do histórico?"

#: main.py:326 main.py:328
#, python-format
msgid ""
"Error deleting log.\n"
"OS error(%s): %s"
msgstr ""
"Erro ao excluir o registro do histórico.\n"
"Erro de SO(%s): %s"

#: main.py:330
#, python-format
msgid ""
"Error deleting log.\n"
"Unexpected error: %s"
msgstr ""
"Erro ao excluir o registro do histórico.\n"
"Erro inesperado: %s"

#: main.py:393
msgid "Application closed!"
msgstr "O aplicativo foi fechado!"

#: main.py:397
#, python-format
msgid ""
"%s is still mounted.\n"
"Do you wish to unmount it before exiting?"
msgstr ""
"%s ainda está montado.\n"
"Você gostaria de desmontá-lo antes de sair?"

#: main.py:408
#, python-format
msgid ""
"Error saving unmounted images to file.\n"
"OS error(%s): %s"
msgstr ""
"Erro ao salvar imagens desmontadas em um arquivo.\n"
"Erro de SO(%s): %s"

#: main.py:410
#, python-format
msgid ""
"Error saving unmounted images to file\n"
"Unexpected error: %s"
msgstr ""
"Erro ao salvar imagens desmontadas em um arquivo.\n"
"Erro inesperado: %s"
