# German translation for furiusisomount
# Copyright (c) 2010 Rosetta Contributors and Canonical Ltd 2010
# This file is distributed under the same license as the furiusisomount package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: furiusisomount\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2010-08-25 11:45+0100\n"
"PO-Revision-Date: 2010-10-03 01:35+0000\n"
"Last-Translator: Klaus Riesterer <Unknown>\n"
"Language-Team: German <de@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-03-21 04:48+0000\n"
"X-Generator: Launchpad (build 16532)\n"

#: aboutbox.py:35
msgid "translator-credits"
msgstr ""
"Launchpad Contributions:\n"
"  Klaus Riesterer https://launchpad.net/~computertechnik-breisnet-online"

#: aboutbox.py:40
msgid "Developer:"
msgstr "Entwickler:"

#: filehash.py:25 filehash.py:36 main.py:246
msgid "Calculating, please wait..."
msgstr "Berechnung - Bitte warten..."

#: globals.py:22
msgid "Furius ISO Mount Tool"
msgstr "Furius ISO Mount Tool"

#: globals.py:23
msgid ""
"Simple Gtk+ Interface to Mount ISO, IMG, BIN, MDF and NRG Image files "
"without burning to disk."
msgstr ""
"Einfache GTK+ Anwendung zum Einbinden von ISO, IMG, BIN, MDF und NRG Images "
"ohne diese auf Disk brennen zu müssen."

#: imageaction.py:35 imageaction.py:58 imageaction.py:69 imageaction.py:79
#: main.py:83 main.py:340 main.py:386
#, python-format
msgid ""
"Error mounting image.\n"
"Unexpected error: %s"
msgstr ""
"Fehler beim Einbinden des Images\n"
"Unerwarteter Fehler: %s"

#: imageaction.py:36
msgid "Defaulting to home directory for mounting."
msgstr "Benutzerverzeichnis als Standard für die Einbindung der Images."

#: imageaction.py:55
#, python-format
msgid ""
"%s successfully mounted @ %s. If required, run the following commands to "
"remove:\n"
"  :fusermount -u %s\n"
"  :rmdir %s"
msgstr ""
"%s erfolgreich eingebunden @ %s. Wenn notwendig, die folgenden Befehle zum "
"Abmelden eingeben:\n"
"  :fusermount -u %s\n"
"  :rmdir %s"

#: imageaction.py:66
#, python-format
msgid ""
"%s successfully mounted @ %s. If required, run the following commands to "
"remove:\n"
"  :gksu -u root umount %s\n"
"  :rmdir %s"
msgstr ""
"%s erfolgreich eingebunden @ %s. Wenn notwendig, die folgenden Befehle zum "
"Abmelden eingeben:\n"
"  :gksu -u root umount %s\n"
"  :rmdir %s"

#: imageaction.py:76 main.py:79 main.py:336 main.py:382
#, python-format
msgid ""
"Error mounting image.\n"
"OS error(%s): %s"
msgstr ""
"Fehler beim Einbinden der Abbilddatei.\n"
"Systemfehler (%s): %s"

#: imageaction.py:103
#, python-format
msgid ""
"Error saving history to file.\n"
"OS error(%s): %s"
msgstr ""
"Fehler beim Speichern der Historie.\n"
"Systemfehler (%s): %s"

#: imageaction.py:106
#, python-format
msgid ""
"Error saving history to file\n"
"Unexpected error: %s"
msgstr ""
"Fehler beim Speichern der Historie.\n"
"Unerwarteter Fehler: %s"

#: imageaction.py:128
#, python-format
msgid "%s successfully unmounted."
msgstr "%s erfolgreich abgemeldet."

#: imageaction.py:130 main.py:358 main.py:401
#, python-format
msgid ""
"Error unmounting image.\n"
"Unexpected error: %s"
msgstr ""
"Fehler beim Abmelden der Abbilddatei.\n"
"Unerwarteter Fehler: %s"

#: imageaction.py:142 main.py:364
#, python-format
msgid ""
"Error burning image.\n"
"Unexpected error: %s"
msgstr ""
"Fehler beim Brennen der Abbilddatei.\n"
"Unerwarteter Fehler: %s"

#: imageaction.py:152
#, python-format
msgid ""
"Error launching nautilus.\n"
"Unexpected error: %s"
msgstr ""
"Fehler beim Start von Nautilus.\n"
"Unerwarteter Fehler: %s"

#: main.py:51
msgid "Application started..."
msgstr "Programm gestartet..."

#: main.py:81 main.py:338 main.py:384
#, python-format
msgid ""
"Error mounting image.\n"
"IO error(%s): %s"
msgstr ""
"Fehler beim Einbinden der Abbilddatei:\n"
"Ein-Ausgabefehler (%s): %s"

#: main.py:95 main.py:112
#, python-format
msgid ""
"Error loading history.\n"
"OS error(%s): %s"
msgstr ""
"Fehler beim Laden der Historie.\n"
"Systemfehler (%s): %s"

#: main.py:97 main.py:114
#, python-format
msgid ""
"Error loading history.\n"
"Unexpected error: %s"
msgstr ""
"Fehler beim Laden der Historie.\n"
"Unerwarteter Fehler: %s"

#: main.py:125
#, python-format
msgid ""
"Error creating settings directory.\n"
"OS error(%s): %s"
msgstr ""
"Fehler beim Anlegen des Konfigurations--Ordners\n"
"Systemfehler (%s): %s"

#: main.py:127
#, python-format
msgid ""
"Error creating settings directory.\n"
"IO error(%s): %s"
msgstr ""
"Fehler beim Anlegen des Konfigurations--Ordners.\n"
"Ein- Ausgabefehler(%s): %s"

#: main.py:129
#, python-format
msgid ""
"Error creating settings directory.\n"
"Unexpected error: %s"
msgstr ""
"Fehler beim Anlegen des Konfigurations--Ordners.\n"
"Unerwarteter Fehler: %s"

#: main.py:139
#, python-format
msgid "New settings file created at %s"
msgstr "Neue Konfigurationsdatei wurde in %s gespeichert"

#: main.py:141
#, python-format
msgid ""
"Error creating settings file.\n"
"OS error(%s): %s"
msgstr ""
"Fehler beim Anlegen der Konfigurationsdatei.\n"
"Systemfehler (%s): %s"

#: main.py:143
#, python-format
msgid ""
"Error creating settings file.\n"
"IO error(%s): %s"
msgstr ""
"Fehler beim Anlegen der Konfigurationsdatei.\n"
"Ein- Ausgabefehler (%s): %s"

#: main.py:145
#, python-format
msgid ""
"Error creating settings file.\n"
"Unexpected error: %s"
msgstr ""
"Fehler beim Anlegen der Konfigurationsdatei.\n"
"Unerwarteter Fehler: %s"

#: main.py:159
msgid "_Browse..."
msgstr "_Durchsuchen …"

#: main.py:163
msgid "_Mount"
msgstr "_Einbinden"

#: main.py:167 main.py:234 main.py:260
msgid "_Checksum"
msgstr "_Prüfsumme"

#: main.py:171
msgid "Bur_n"
msgstr "_Brennen"

#: main.py:175
msgid "_Unmount"
msgstr "_Abmelden"

#: main.py:176
msgid "View Log"
msgstr "Protokoll anzeigen"

#: main.py:177
msgid "Delete Log"
msgstr "Protokoll löschen"

#: main.py:178
msgid "Select Image"
msgstr "Abbilddatei wählen"

#: main.py:179 main.py:289 main.py:308
msgid "No Image Selected"
msgstr "Keine Abbilddatei gewählt"

#: main.py:181 main.py:248
msgid "No Checksum Generated"
msgstr "Keine Prüfsumme generiert"

#: main.py:183 main.py:355
msgid "No Mount Point Selected"
msgstr "Kein Einhängepunkt gewählt"

#: main.py:185
msgid "Mounted Images:"
msgstr "Eingebundenen Abbilddateien:"

#: main.py:186
msgid "Drag image files into above window to quickly mount"
msgstr ""
"Für das schnelle Einbinden die Abbilddatei in das obige Fenster ziehen"

#: main.py:196
msgid "Mount Point"
msgstr "Einhängepunkt (Mount-Point)"

#: main.py:197
msgid "Image File"
msgstr "Abbilddatei:"

#: main.py:236
msgid "_Cancel"
msgstr "_Abbrechen"

#: main.py:240
msgid "Checksum generation started..."
msgstr "Prüfsumme wird erstellt..."

#: main.py:256
#, python-format
msgid "%s:%s"
msgstr "%s:%s"

#: main.py:259
msgid "Checksum generation aborted!"
msgstr "Erstellung der Prüfsumme abgebrochen!"

#: main.py:268
msgid "Open Image.."
msgstr "Abbilddatei öffnen.."

#: main.py:288
msgid ""
"File not found. \n"
"Please check source exists."
msgstr ""
"Datei nicht gefunden. \n"
"Bitte prüfen, ob die Quelle existiert."

#: main.py:307
msgid ""
"File does not appear to be a compatible Image. \n"
"Please check source."
msgstr ""
"Datei scheint keine passende oder gültige Abbilddatei zu sein. \n"
"Bitte die Quelle prüfen."

#: main.py:318
#, python-format
msgid "%s not found."
msgstr "%s nicht gefunden."

#: main.py:322
msgid "Are you sure you wish to delete the log?"
msgstr "Sind Sie sicher, dass Sie das Protokoll löschen möchten?"

#: main.py:326 main.py:328
#, python-format
msgid ""
"Error deleting log.\n"
"OS error(%s): %s"
msgstr ""
"Fehler beim Löschen des Protokolls.\n"
"Systemfehler (%s): %s"

#: main.py:330
#, python-format
msgid ""
"Error deleting log.\n"
"Unexpected error: %s"
msgstr ""
"Fehler beim Löschen des Protokolls.\n"
"Unerwarteter Fehler: %s"

#: main.py:393
msgid "Application closed!"
msgstr "Programm geschlossen!"

#: main.py:397
#, python-format
msgid ""
"%s is still mounted.\n"
"Do you wish to unmount it before exiting?"
msgstr ""
"%s ist noch eingebunden.\n"
"Soll diese vor dem Beenden abgemeldet werden?"

#: main.py:408
#, python-format
msgid ""
"Error saving unmounted images to file.\n"
"OS error(%s): %s"
msgstr ""
"Fehler beim Speichern abgemeldeter Abbilddateien in die Datei.\n"
"Systemfehler (%s): %s"

#: main.py:410
#, python-format
msgid ""
"Error saving unmounted images to file\n"
"Unexpected error: %s"
msgstr ""
"Fehler beim Speichern abgemeldeter Abbilddateien in die Datei.\n"
"Unerwarteter Fehler: %s"
